version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bankcore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bankcore
      MYSQL_DATABASE: bankcore
      MYSQL_USER: bankcore
      MYSQL_PASSWORD: bankcore
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/mysql-schema.sql:/docker-entrypoint-initdb.d/mysql-schema.sql:ro
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: bankcore-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
