spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/bankcore?useSSL=false&serverTimezone=UTC
    username: bankcore
    password: bankcore
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
account-service:
  url: http://localhost:8081
customer-service:
  url: http://localhost:8082
risk-service:
  url: http://localhost:8086
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
payment:
  messaging:
    exchange: payment.events.exchange
    queue: payment.events.queue
    routingKey: payment.events
    dlq: payment.events.dlq
